# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll-theme-cayman", "~> 0.1"

gem "github-pages", group: :jekyll_plugins

